# Generated by Django 5.1.7 on 2025-03-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('paper_title', models.CharField(blank=True, max_length=255, null=True)),
                ('paper_number', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_papers', models.IntegerField(default=1)),
                ('student_status', models.IntegerField(choices=[(0, 'Student'), (1, 'Non-Student')])),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
