# Generated by Django 5.1.2 on 2025-04-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_registrationinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
